### ISSUE TITLE
请教下 这个实现原理或需要用什么库来支持，有对应iOS平台的方案吗？

### ISSUE THREAD

**Issue by bluesky0109** [lihangleo2/AirRelationView#1]
请教下 这个实现原理或需要用什么库来支持，有对应iOS平台的方案吗？

**Comment by lihangleo2** [comment]
这个完全就是自定义控件，底部自定义画线的view,上层通过addView加入图片控件。缺点就是不支持复用，所有大量的图片的时候暂时无法解决。上下左右滑用的是一个第三方的scorllView。然后nineoldandroids.jar去控制双指缩放倍数。ios也是这样的思路
